---
application:
  name: "myplace-backend"
  project: "myplace-backend"
  organization: "QoveryCommunity"
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: "myplace-backend"
    paths:
    - "/*"
