---
application:
  name: "myplace-backend"
  project: "myplace-backend"
  organization: "QoveryCommunity"
routers:
- name: "main-myplace-backend"
  routes:
  - application_name: "myplace-backend"
    paths:
    - "/*"
